id: P010510
initial_creation_type: ocr
source_metadata:
  id: bdr:W22069
  title: མེ་གླིང་གཡུལ་འཁྲུག
  author: ''
  volumes:
    41f60f74ed4a4239a68e915809a29d15:
      image_group_id: I1KG17273
      title: ''
      volume_number: 1
      total_pages: 342
